# Запускаем магию только на пуши в main
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET 6
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true

        # Generate the website
        - name: Publish
          run: dotnet publish editor.csproj --configuration Release --output release --nologo

          # отключаем jekyll
        - name: Add .nojekyll file
          run: touch release/wwwroot/.nojekyll

        - name: Uploading files to gh-pages branch
          uses: JamesIves/github-pages-deploy-action@4.1.4
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            branch: gh-pages
            folder: release/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
