name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET 6
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true

        # Generate the website
        - name: Publish
          run: dotnet publish editor.csproj --configuration Release --output release --nologo

        # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
        - name: Add .nojekyll file
          run: touch release/wwwroot/.nojekyll

        - name: Uploading files to gh-pages branch
          uses: JamesIves/github-pages-deploy-action@4.1.4
          with:
            branch: gh-pages
            folder: release/wwwroot
